### ISSUE TITLE
Group same context components 

### ISSUE THREAD

**Issue by leocavalcante** [multisolution/multi#92]
- [ ] Can we move this https://github.com/multisolution/multi/blob/master/web/components/form-msg.tsx to the Form module: https://github.com/multisolution/multi/blob/master/web/components/form.tsx since they are in the same context?

- [ ] Is this being used? https://github.com/multisolution/multi/blob/master/web/components/title-page.tsx Can we move it to, maybe the layout module? Or does it really deserves a module for its own?

**Comment by carloswilliamds** [comment]
> * [ ]  Can we move this https://github.com/multisolution/multi/blob/master/web/components/form-msg.tsx to the Form module: https://github.com/multisolution/multi/blob/master/web/components/form.tsx since they are in the same context?
This is no longer needed in the application.

> * [ ]  Is this being used? https://github.com/multisolution/multi/blob/master/web/components/title-page.tsx Can we move it to, maybe the layout module? Or does it really deserves a module for its own?
This component is used profile and list-users pages. Im move to global-style.
